### PR TITLE
Consume LSP4J 0.9.0

### LINKED ISSUE #237: Consume LSP4J 0.9.0
Consume last version of LSP4J 0.9.0. It requires some code changes because LSP4J 0.9.0 breaks some API.

### PR DESCRIPTION
**Pull request by angelozerr**
Consume LSP4J 0.9.0

Fixes #237

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
Just wondering on the effect for the next release of JBoss Tools which will be based on 2020-03 ?

**Comment by angelozerr** [comment]
> Just wondering on the effect for the next release of JBoss Tools which will be based on 2020-03 ?

Ok I remove the 0.9.0 constraints on JDT LS side. So now there is only MicroProfile LS which depends on  0.9.0, so I think it should work.

But for https://github.com/redhat-developer/quarkus-ls/issues/236 I need 0.9.0 on JDT LS side because JDT LS depends on 0.9.0 and I have a compilation problem with Diagnostic#getCode():

 * in 0.8.1 Diagnostic#getCode() returns just a String
 * in 0.9.0 Diagnostic#getCode() returns String or Number (with Either).

Perhaps I could use jav areflection to support 0.8.1 and 0.9.0 to get the code to support the both lsp4j version. @fbricon what do you think about that?

**Comment by angelozerr** [comment]
@jeffmaury could you test my PR and check it works with Eclipse IDE / LSP4E which consumes lsp4j 0.8.1. Thanks for your feedback.

**Comment by jeffmaury** [comment]
Just installed latest 2019-03 and they are using LSP4J 0.9.0 so we should be good for next release of JBoss Tools

**Comment by angelozerr** [comment]
Great thanks @jeffmaury for your feedback. So I add this contstraint to the MANIFEST.MF of JDT plugins.

**Pull request merged**
