### PR TITLE
Move to LSP4j 0.13.0

### LINKED ISSUE #644: Move to LSP4j 0.13.0

### PR DESCRIPTION
**Pull request by angelozerr**
Move to LSP4j 0.13.0

Fixes #644

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR requires https://github.com/redhat-developer/vscode-quarkus/pull/506

**Comment by fbricon** [comment]
@rgrunber can you check this update won't break in Theia, pretty please?

**Comment by angelozerr** [comment]
> @angelozerr there are 5 failures in https://github.com/redhat-developer/quarkus-ls/pull/645/checks

Ooops goot catch, it should be fixed.

**Review by AlexXuChen — COMMENTED** [review]
InlayHint is still working properly:
Screenshot from 2022-06-08 16-48-49
One thing to note is that I needed to make updates to `https://download.eclipse.org/jdtls/snapshots/repository/latest`, similar to https://github.com/redhat-developer/quarkus-ls/pull/577/files#diff-ff34482d69102e42f3609f3b86315fdbafa8e9cf44fd676b3a1f7f1d8fb93ed2R41

**Pull request merged**
