### PR TITLE
Support for <mp-rest-client-class-name>/mp-rest/providers/*/priority

### PR DESCRIPTION
**Pull request by angelozerr**
Support for /mp-rest/providers/*/priority

See https://github.com/redhat-developer/quarkus-ls/issues/189

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR supports last mp-rest property `<mp-rest-client-class-name>/mp-rest/providers/<mp-provider-class-name>/priority`. You will have completion about this property. But as it's a complex property you need to add in your settings this validation rule:

```json
"quarkus.tools.validation.unknown.excluded": [
        "*/mp-rest/providers/*/priority"
    ]
```

to avoid having an error. When https://github.com/redhat-developer/quarkus-ls/issues/203 will be supported, it will fix that without this settings.

I will do a PR in vscode-quarkus to explain this settings.

**Comment by angelozerr** [comment]
See my pr https://github.com/redhat-developer/vscode-quarkus/pull/203 about settings

**Comment by xorye** [comment]
This PR works/looks good for me

I know this isn't part of this PR but I don't understand what's being done with `itemHint` here? 
https://github.com/redhat-developer/quarkus-ls/blob/db1039a9f8b5eb20c95dcaabf140c4b9ab11287f/microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/providers/MicroProfileRegisterRestClientProvider.java#L162-L177
It's being created and a value is being added to it but it looks like the code doesn't do anything with it after that?

**Comment by angelozerr** [comment]
> Oops, nevermind about this, I noticed getItemHint() adds the hint to the hintsCache

Yes that's it :)

If you think we can merge the PR, please do it!

**Comment by xorye** [comment]
@angelozerr one small thing, is it possible to escape the `<` and `>` characters in your commit message? 

So that we could have `Support for <mp-rest-client-class-name>/mp-rest/providers/*/priority` instead of `Support for /mp-rest/providers/*/priority` ?

**Comment by angelozerr** [comment]
@xorye commit has been changed

**Comment by xorye** [comment]
Could we try the Travis test again?

**Pull request merged**
