### PR TITLE
textDocument/inlayHint fails when classpath is incorrect

### LINKED ISSUE #858: textDocument/inlayHint fails when classpath is incorrect
- create a Quarkus Maven project
- add an invalid dependency, eg:
```xml
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>missing</artifactId>
      <version>9.9.9</version>
    </dependency>
```
- create a user tag as src/main/resources/templates/tags/mytag.html, containing simply `{nested-content}`
- create a qute template as src/main/resources/templates/index.html, containing 
```
{#mytag}
foo
{/}
```

The Qute LS throws an exception that pops up in the user's face:

Screenshot 2023-04-05 at 12 47 36

Cause:

> Received response 'textDocument/inlayHint - (91)' in 10ms. Request failed: Request qute/template/userTags failed with message: /Users/fbricon/.m2/repository/io/quarkus/missing/9.9.9/missing-9.9.9.jar does not exist (-32603).
[Error - 12:51:47] Request textDocument/inlayHint failed.
  Message: Request qute/template/userTags failed with message: /Users/fbricon/.m2/repository/io/quarkus/missing/9.9.9/missing-9.9.9.jar does not exist
  Code: -32603

### PR DESCRIPTION
**Pull request by angelozerr**
textDocument/inlayHint fails when classpath is incorrect

Fixes #858

### CODE REVIEW

**Comment by fbricon** [comment]
Can you check that other usages of IPackageFragmentRoot are guarded too? Also maybe check in lsp4mp

See:
- https://github.com/search?q=repo%3Aredhat-developer%2Fquarkus-ls%20IPackageFragmentRoot&type=code
- https://github.com/search?q=repo%3Aeclipse%2Flsp4mp%20IPackageFragmentRoot&type=code

**Comment by angelozerr** [comment]
Good catch @fbricon, this check must be done only when `project.getPackageFragmentRoot` is called:

 * I fix that for QuarkusConfigProvider
 * for LSP4MP no need to do that

**Comment by angelozerr** [comment]
@fbricon can we merge the PR?

**Comment by fbricon** [comment]
Thanks @angelozerr!

**Pull request merged**
