### PR TITLE
Support Jakarta namespace for Quarkus 3

### LINKED ISSUE #779: Quarkus 3 support
I'm making this issue to keep track of changes that will need to be made related to Quarkus 3.

Among other things, Quarkus 3 migrates the EE classes from the `javax` namespace to the `jakarta` namespace.

### PR DESCRIPTION
**Pull request by datho7561**
Closes #779

Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
I should include tests that test the changes with a Quarkus 3 project, although it would probably be a good idea to wait until Quarkus 3 is released in order to do that.

**Comment by datho7561** [comment]
@maxandersen This PR is to fix support for Quarkus 3 in vscode-quarkus. (It's fixes related to the jakarta namespace migration for features in the qute templating support). It still needs a bit of work, and currently I'm writing integration tests on a Quarkus project using one of the alpha builds. How far out is the Quarkus 3 release? I'm wondering if I should hold off on this until a release/release candidate version of Quarkus 3 is available.

**Comment by maxandersen** [comment]
I would put it in as soon as possible to make it easy to try out. As long as it can still work with quarkus 2 :)

**Comment by datho7561** [comment]
Okay. Sounds good. I'll get this polished up and merged.

**Comment by datho7561** [comment]
Just to explain what's changed in this PR:
- Referencing a `@Named` bean from a template using `inject:NameOfBean` should work for Quarkus 3 projects
- If you add `@Vetoed` or `@Decorator` (from jakarta the namespace) to your `@Named` bean, you will no longer be able to reference it in a template, since adding these annotations prevents the class from being a bean class.

**Comment by angelozerr** [comment]
It works great, thanks @datho7561 !

**Pull request merged**
