### PR TITLE
Update Jenkinsfile to use Java 17

### PR DESCRIPTION
**Pull request by datho7561**
Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
Will the produced JAR be compatible with Java 11 ?

**Comment by rgrunber** [comment]
Note that JDT-LS & any component we contribute to that part of the runtime (eg. `org.eclipse.lsp4mp.jdt.core`, `com.redhat.microprofile.jdt.quarkus`, `com.redhat.qute.jdt`) will require a Java 17 runtime.

The lsp4mp language servers (eg. `org.eclipse.lsp4mp.ls`), and the extension for it ( `com.redhat.quarkus.ls` ), as well as the Qute LS (`com.redhat.qute.ls`) should continue to work with a Java 11 runtime.

**Review by rgrunber — APPROVED** [review]

**Comment by rgrunber** [comment]
@jeffmaury , would it be possible to continue using the previous versions. For 2022-09, I would think many bundles could transiation to BREE of JavaSE-17.

For references :

https://www.eclipse.org/lists/cross-project-issues-dev/msg19177.html
https://wiki.eclipse.org/SimRel/Simultaneous_Release_Requirements#Execution_Environment_.28partially_tested.29

**Comment by rgrunber** [comment]
Going to merge for now as with m2e -> JDT-LS -> lsp4mp/quarkus-ls extensions needing Java 17, I don't think there's much we can do. We needed m2e 2.0 for https://github.com/eclipse/eclipse.jdt.ls/issues/2085 .

**Pull request merged**
