### PR TITLE
Parameter declaration support improvement

### LINKED ISSUE #459: Parameter declaration support  improvement
There are some NPE when parameter declaration is used (ex : higlight a class which doesn't define an alias). Completion of classes should be improved (ex : today we return all classes when no class is defined which could be very bad for performance).

In some cases, completion of class doesn't work (ex : when a alias is defined and some class is defined)

When an alias is defined (without class),the apply of completion generate a new alias.

This support has been developedquickly, many tests should be written to be have a parameter declaration more robust.

### PR DESCRIPTION
**Pull request by angelozerr**
Parameter declaration support improvement

Fixes #459

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR starts working, here a demo:

QuteParameterDeclarationDemo

I need to improve again:

 * write tests for JDT side
 * try to support generic (generate java.util.List<>
 * manage completion for packages (ex : java. should provide util package etc)

**Comment by fbricon** [comment]
if you type `{@java.util.List<Ite|}` and select the proper Item type, it'll complete with `{@java.util.List<org.acme.Item item}` instead of  `{@java.util.List<org.acme.Item> item}`

**Comment by angelozerr** [comment]
> if you type {@java.util.List<Ite|} and select the proper Item type, it'll complete with {@java.util.List<org.acme.Item item} instead of {@java.util.List<org.acme.Item> item}

It should be fixed

**Comment by jeffmaury** [comment]
Draft and review, sounds silly to me, is it ok to review ?

**Comment by angelozerr** [comment]
> Draft and review, sounds silly to me, is it ok to review ?

I need to write tests again and clean some piece of code (it's the reason why it is in draft). Otherwise features like generic should work:

QuteParameterDeclarationDemo2

**Comment by angelozerr** [comment]
My code is now cleaned and tests are written. I must just write à last test on qute ls side with generic type parameter. 

So you can review it. Thanks.

**Comment by angelozerr** [comment]
Ok all  tests are written now. The PR is ready to review!

**Comment by jeffmaury** [comment]
`{@qute1.MyData }` not reported as error

**Comment by jeffmaury** [comment]
```
{@
{data.available}
{#with data}
{#with stringCollection}
{}
{/with}
{/with}
```

Code assist is NOP after `{@`

**Comment by angelozerr** [comment]
> {@qute1.MyData } not reported as error

Indeed but it's a syntax error validation and the real Qute parser doesn't report this kind of error. I process real Qute parser when validation is done and it should report it, but today it doesn't report it. My idea is that Qute use my parser (see https://github.com/redhat-developer/quarkus-ls/issues/473) and provide validator for that.

In other words I would like to support syntax error in https://github.com/redhat-developer/quarkus-ls/issues/473

**Comment by mkouba** [comment]
> > {@qute1.MyData } not reported as error
> 
> Indeed but it's a syntax error validation and the real Qute parser doesn't report this kind of error. I process real Qute parser when validation is done and it should report it, but today it doesn't report it. My idea is that Qute use my parser (see #473) and provide validator for that.
> 
> In other words I would like to support syntax error in #473 (/cc @mkouba )

Yes, I think that this kind of error should result in a parser error. I'll fix the current parser right away.

**Comment by angelozerr** [comment]
> Yes, I think that this kind of error should result in a parser error. I'll fix the current parser right away.

Thanks! @mkouba let me some time to support all Qute syntaxes with my Qute parser and discuss in  #473 if you think it's a good idea to adopt my parser. The benefit with my parser is that I support start/end offset for each nodes. So it's easy to give the right position.

**Comment by angelozerr** [comment]
> Code assist is NOP after {@

It was a parser problem, it should be fixed with tests.

**Comment by fbricon** [comment]
So if you have a nested class foo.bar.Item.NestedItem, 
{@foo proposes  foo.bar.Item.NestedItem
but {@foo.bar.Item.Nest doesn't

**Comment by angelozerr** [comment]
> So if you have a nested class foo.bar.Item.NestedItem, {@foo proposes foo.bar.Item.NestedItem but {@foo.bar.Item.Nest doesn't

It should be fixed.

**Comment by fbricon** [comment]
@angelozerr  it's better, but now, if you do {@foo.bar.Ite|, only foo.bar.Item is proposed,  missing foo.bar.Item.NestedItem

**Comment by fbricon** [comment]
Thanks @angelozerr!

**Pull request merged**
