### PR TITLE
Missing enum value completion/validation for optional enum

### LINKED ISSUE #175: Missing enum value completion/validation for optional enum
For the following properties: 
```
quarkus.hibernate-search.elasticsearch.automatic-indexing.synchronization-strategy
quarkus.hibernate-search.elasticsearch.backends.{*}.automatic-indexing.synchronization-strategy
quarkus.hibernate-search.elasticsearch.backends.{*}.index-defaults.lifecycle.strategy
quarkus.hibernate-search.elasticsearch.backends.{*}.index-defaults.lifecycle.required-status
quarkus.hibernate-search.elasticsearch.backends.{*}.indexes.{*}.lifecycle.strategy
quarkus.hibernate-search.elasticsearch.backends.{*}.indexes.{*}.lifecycle.required-status
```
each of these properties expect a `java.util.Optional<ENUM VALUE>` as its value. However, when invoking completion for the value, there are no completion options for the enum value.

Also, there is no value validation, meaning that there is no error diagnostic if the value is not a valid enum value.

### PR DESCRIPTION
**Pull request by angelozerr**
Missing enum value completion/validation for optional enum

Fixes #175

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Here a demo with `quarkus.datasource.transaction-isolation-level` which have optional value type 
`java.util.Optional<io.agroal.api.configuration.AgroalConnectionFactoryConfiguration.TransactionIsolation>` OptionalEnumDemo

**Comment by xorye** [comment]
If I go to definition for the enum value for `quarkus.datasource.transaction-isolation-level`, I see the following:
image

Therefore, I think we should have `repeatable-read` as a completion option:
image

image

**Comment by fbricon** [comment]
we no longer have value completion for quarkus.log.console.async.overflow= (see https://github.com/redhat-developer/quarkus-ls/issues/2)
Also, enum values don't seem proposed in application.yaml

**Comment by angelozerr** [comment]
Sorry guys my PR was so bad. It worked because values for isolation level was hard coded. (the problem described in https://github.com/redhat-developer/quarkus-ls/pull/197#issuecomment-577311311)

All problem should be fixed:

 * the REPEATABLE_READ should be shown in the completion
 * quarkus.log.console.async.overflow property (No optional enum) should work
 * quarkus.datasource.transaction-isolation-level (optional enum) should work on YAML too

BUT we don't manage correctly value for enum. According the documentation we should have `repeatable-read` instead of having `REPEATABLE_READ `

**Pull request merged**
