### PR TITLE
Validation fail when iterating over integers

### LINKED ISSUE #511: Validation fail when iterating over integers
According to https://quarkus.io/guides/qute-reference#loop_section

```
The for statement also works with integers, starting from 1. In the example below, considering that total = 3:

{#for i in total}
  {i}:
{/for}
And the output will be:

1:2:3:

```
But the qute ls complains about it:

Screenshot 2022-01-05 at 15 32 09

### PR DESCRIPTION
**Pull request by angelozerr**
Validation fail when iterating over integers

Fixes #511

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
It should work but I need to write test and clean code.

**Comment by fbricon** [comment]
looks like you don't get anything when hovering over `i` in, while hovering over `total` shows `int` 
```
{#for i in total}
  {i}:
{/}
```

**Comment by angelozerr** [comment]
> looks like you don't get anything when hovering over i in, while hovering over total shows int

try to rename i with foo (to have a longer variable), I think it should work.

**Comment by angelozerr** [comment]
> looks like you don't get anything when hovering over i in, while hovering over total shows int

I improved the hover position and now I accept this usecase:

```
{#for i in total}
  {|i}:
{/}
```

when hover/definition is done after a start expression, I include the part.

**Comment by angelozerr** [comment]
Here a demo:

IntegersDemo

**Comment by fbricon** [comment]
thanks @angelozerr !

**Pull request merged**
