### PR TITLE
`quarkus.banner.enabled` marked as error

### PR DESCRIPTION
**Pull request by angelozerr**
`quarkus.banner.enabled` marked as error

Fixes https://github.com/redhat-developer/vscode-quarkus/issues/249

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR should fix the https://github.com/redhat-developer/vscode-quarkus/issues/249
 I need to write tests.

**Comment by angelozerr** [comment]
Test is written

**Comment by fbricon** [comment]
[Build fails](https://travis-ci.org/github/redhat-developer/quarkus-ls/builds/679091878?utm_source=github_status&utm_medium=notification):
> Failures: 
  ConfigItemIntBoolDefaultValueTest.configItemIntBoolDefaultValueTest:33 expected:<196> but was:<275>
  MicroProfileConfigPropertyTest.configQuickstartFromClasspath:45 expected:<196> but was:<275>

**Comment by angelozerr** [comment]
Tests are fixed

**Comment by fbricon** [comment]
I see a couple issues here:
* quarkus..default-locale ???
* quarkus.banner.default_banner_file was proposed for completion  but at runtime, there's an error: `Unrecognized configuration key "quarkus.banner.default_banner_file" was provided; it will be ignored`

Screen Shot 2020-04-26 at 7 43 57 PM

**Comment by angelozerr** [comment]
> quarkus..default-locale ???

fixed and test are written with this new usecase.

> quarkus.banner.default_banner_file

This property comes from the static private field from https://github.com/quarkusio/quarkus/blob/d890466091be6954d08e939ca32f777db49a73c1/core/runtime/src/main/java/io/quarkus/runtime/LocalesBuildTimeConfig.java#L14

In my new patch I ignore static fields or private fields like https://github.com/quarkusio/quarkus/blob/6c6fc37acf88b02613cc1f59684f26664dfe71be/core/processor/src/main/java/io/quarkus/annotation/processor/ExtensionAnnotationProcessor.java#L501 but I need to check that and adjust tests.

**Comment by fbricon** [comment]
@gsmet @emmanuelbernard should static fields be ignored when computing available properties?

**Comment by angelozerr** [comment]
@fbricon all tests has been fixed.

**Comment by gsmet** [comment]
@fbricon I would say you can ignore them, yes.

**Comment by gsmet** [comment]
But I would go even further and only consider fields marked with `@ConfigItem`.

**Pull request merged**
