### PR TITLE
Fix completion with @TemplateExtension

### PR DESCRIPTION
**Pull request by angelozerr**
Fix completion with @TemplateExtension

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
Completion is there, now I wonder if we shouldn't display the method as halfPrice() instead of halfPrice(Item item)
Screenshot 2021-12-14 at 16 33 55

**Comment by angelozerr** [comment]
> Completion is there, now I wonder if we shouldn't display the method as halfPrice() instead of halfPrice(Item item)

I agree, I create an issue for that at https://github.com/redhat-developer/quarkus-ls/issues/490

**Comment by angelozerr** [comment]
I fixed the conflicts, PR is ready.

**Comment by angelozerr** [comment]
@fbricon can we merge this PR?

**Pull request merged**
