### PR TITLE
Add support for properties defined in Scheduled annotations.

### PR DESCRIPTION
**Pull request by rgrunber**
- Fixes redhat-developer/vscode-quarkus#319
- Add testcases

Signed-off-by: Roland Grunberg <rgrunber@redhat.com>

Note : This needs an addition to the MavenProjectName enum in lsp4mp for the tests to compile. Is that the right approach to test Scheduled annotations ?

### CODE REVIEW

**Comment by angelozerr** [comment]
> Note : This needs an addition to the MavenProjectName enum in lsp4mp for the tests to compile. Is that the right approach to test Scheduled annotations ?

Indeed it's very bad. Is there any chance that you could work on that on LSP4MP side too?

**Comment by angelozerr** [comment]
Please fix the conflicts

**Comment by rgrunber** [comment]
> > Note : This needs an addition to the MavenProjectName enum in lsp4mp for the tests to compile. Is that the right approach to test Scheduled annotations ?
> 
> Indeed it's very bad. Is there any chance that you could work on that on LSP4MP side too?

Sure, I'll propose something on the lsp4mp side. If I understand correctly, we would also need to switch to the snapshot releases of lsp4mp in the `quarkus-ls/quarkus.jdt.ext` target platform.

**Comment by angelozerr** [comment]
> Sure, I'll propose something on the lsp4mp side. If I understand correctly, we would also need to switch to the snapshot releases of lsp4mp in the quarkus-ls/quarkus.jdt.ext target platform.

Thanks @rgrunber. An idea is to replace MavenProject enumeration with an interface IMavenProject and the current MavenProject from microprofile should extend IMavenProject. Quarkus test could contribute to test by implementing IMavenProject by a QuarkusMavenProject for instance.

**Comment by rgrunber** [comment]
I should probably bump to the snapshot releases in the target platform, otherwise this won't build.

**Comment by rgrunber** [comment]
I noticed `.classpath` and `.project` weren't uploaded (likely due to gitignore) so hopefully that was the issue.

**Comment by angelozerr** [comment]
Thanks @rgrunber !

**Pull request merged**
