### PR TITLE
Indent snippet new line if LSP client doesn't support InsertTextMode#AdjustIndentation

### LINKED ISSUE #727: Indent snippet new line if LSP client doesn't support `InsertTextMode#AdjustIndentation`
In Eclipse IDE, the snippet section doesn't generate correctly the line identation (for new ines)

EclipseInlayHintDemo

After reading https://github.com/microsoft/language-server-protocol/issues/83, I noticed that Eclipse IDE doesn't support `InsertTextMode#AdjustIndentation`, it means that we need to check this mode (coming from LSP client capability) and generate the proper line indentation in this case.

### PR DESCRIPTION
**Pull request by angelozerr**
Indent snippet new line if LSP client doesn't support InsertTextMode#AdjustIndentation

Fixes #727

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
I have tested this PR on Eclipse IDE and it works correctly. Please test this PR with vscode by checking that completion snippet (like #for with some indentation before it) continue to work.

**Comment by datho7561** [comment]
It appears to still work correctly in VS Code

**Comment by angelozerr** [comment]
If you think the code is good, please merge it. My tests should cover all usecases.

**Comment by datho7561** [comment]
The code looks good. I want to test it in Eclipse myself, but I couldn't figure out how to compile https://github.com/jbosstools/jbosstools-quarkus

**Review by datho7561 — APPROVED** [review]
Works well! Thanks again for your help in getting qute-ls working in Eclipse!

**Pull request merged**
