### PR TITLE
Use lsp4mp `0.8.0-SNAPSHOT`

### PR DESCRIPTION
**Pull request by datho7561**
Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Comment by datho7561** [comment]
This is failing, since no lsp4mp 0.8.0 SNAPSHOTS have been published (since the build failed)

**Comment by datho7561** [comment]
I managed to get the tests to pass locally, they are just very flaky

**Comment by rgrunber** [comment]
You could also switch to using https://repo.eclipse.org/content/repositories/jdtls-snapshots/org/eclipse/jdt/ls/org.eclipse.jdt.ls.tp/1.23.0-SNAPSHOT/ .

**Comment by datho7561** [comment]
Alright, I've updated jdt.ls

**Pull request merged**
