### PR TITLE
Validate overloaded methods

### PR DESCRIPTION
**Pull request by angelozerr**
Validate overloaded methods

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
This PR improves validation:

 * for template extension when it is not applicable for teh base object:
 
image

 * for method which have same name but with several signatures (like String.getBytes):

image

**Comment by angelozerr** [comment]
Please note this PR uses parameter types for validation. Hover and definition doesn't use those parameter types because it will require a lot of refactoring to compute parameter types which is done for the moment in diagnostics only.

When you hover getBytes, you will see type of the first getBytes, so the hover can be wrong for parameters. I would liketo do that in an another PR in the future.

**Comment by fbricon** [comment]
If I have an extension method halfPrice(Item item), when calling {item.halfPrice()} I get an "The virtual method `halfPrice` in the type `TemplateExtensions` is not applicable for the base object `Item` type." error message, but Quarkus is totally fine running with it.

**Comment by angelozerr** [comment]
> If I have an extension method halfPrice(Item item), when calling {item.halfPrice()} I get an "The virtual method halfPrice in the type TemplateExtensions is not applicable for the base object Item type." error message, but Quarkus is totally fine running with it.

Oooops sorry, I introduced a bug , I have noticed that because test doesn't covered this usecase. Now it should be fixed with test.

**Comment by fbricon** [comment]
thanks @angelozerr

**Pull request merged**
