### PR TITLE
Initialize Qute syntax validator with fault tolerant to support section errors

### LINKED ISSUE #812: Hovering "missing close tag" parser error yields `Exception` in CodeAction code
Here is an example Qute template:

```
<html>

{! {#switch myString}
  {#case "asdf"}
  <h3>title</h3>
{/switch} !}

{#each items}

{#each items}
  {it.name}
{/each}

{#each items}

{#each items}
  {it.name}
{/each}



{/}

<p>
</p>

</html>
```

The error appears in the wrong place (it should be at the end of the file), and when you hover it, there is an Exception in the CodeAction code:

```
Mar. 13, 2023 12:15:55 P.M. com.redhat.qute.services.QuteCodeActions doCodeActions
SEVERE: Failed creating CodeAction Request
com.redhat.qute.ls.commons.BadLocationException: The character value, {7} of the line24}, is out of bounds.
	at com.redhat.qute.ls.commons.TreeLineTracker.getOffsetAt(TreeLineTracker.java:1246)
	at com.redhat.qute.ls.commons.TextDocument.offsetAt(TextDocument.java:71)
	at com.redhat.qute.parser.template.Template.offsetAt(Template.java:88)
	at com.redhat.qute.services.AbstractPositionRequest.<init>(AbstractPositionRequest.java:34)
	at com.redhat.qute.services.codeactions.CodeActionRequest.<init>(CodeActionRequest.java:51)
	at com.redhat.qute.services.QuteCodeActions.doCodeActions(QuteCodeActions.java:102)
	at com.redhat.qute.services.QuteLanguageService.doCodeActions(QuteLanguageService.java:104)
	at com.redhat.qute.ls.template.TemplateFileTextDocumentService.lambda$codeAction$9(TemplateFileTextDocumentService.java:165)
	at com.redhat.qute.ls.commons.ModelTextDocuments.lambda$computeModelAsyncCompose$1(ModelTextDocuments.java:144)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
```

### PR DESCRIPTION
**Pull request by angelozerr**
Initialize Qute syntax validator with fault tolerant to support section errors

Fixes #812

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
In this PR, I have started  to implement Qute validator for syntax for the real Qute error code:

 * ParserError.SECTION_END_DOES_NOT_MATCH_START
 * ParserError.UNTERMINATED_SECTION

QuteSyntaxValidator improves the syntax validation of the real Qute parser by reporting:
 
 * several errors instead of the first error encountered in the template.
 * a proper range (start/end position) instead of just one position.
 * a proper position instead of reporting strange position with the real Qute parser.

Takes a sample:

```
{#if}
	{#for items}
		{it.name}
	{/each}

	{#for items}
		{it.name}
	{/each}

{#if}
	{#for items}
		{it.name}
	{/each}

	{#for items}
		{it.name}
	{/each}
```

Here a screenshot with the real Qute parser which report just the first error on a position (and not range):

image

Here a demo with the PR:

QuteErrorWithFaultTolerant

**Comment by angelozerr** [comment]
@datho7561 @JessicaJHee you can review the PR.

Here a sample file that you could use:

```html

{#if true}Hello{#else}Hi{/elsa}{/if} {!SECTION_BLOCK_END_DOES_NOT_MATCH_START!}

{# foo=1 /} {! NO_SECTION_NAME !}

{#foo true /} {! NO_SECTION_HELPER_FOUND !}

{#if true}Hello {true}!{/for} {! SECTION_END_DOES_NOT_MATCH_START !}

{#let true}
	Bye...
{/let}
	Hello
{/let} {!SECTION_START_NOT_FOUND,!}

{#if true}Hello {true} {!UNTERMINATED_SECTION!}
```

If you try with the master, you will see just one error with strange error range which uses the real Qute parser:

image


With this PR which uses our fault tolerant parser, you will see :

image

@mkouba @FroMage here a good sample why we need fault tolerant parser with proper location.

**Comment by datho7561** [comment]
Here is a case that isn't handled yet:

```qute-html
{#if asdf??}

{/}

{/}

{/}

{/}
```

**Review by JessicaJHee — APPROVED** [review]
It' looking really good! The only problem I bumped into was that there was no error when I add `{/}` on it's own or after any correct section. edit: meant to leave as a comment, not approval 

```
{#if condition}
	
{/if}
{/}
```

**Comment by JessicaJHee** [comment]
> ```
> {#if condition}
> 	
> {/if}
> {/}
> ```

ops seems like it's the same case as David mentioned

**Comment by angelozerr** [comment]
> Here is a case that isn't handled yet:

It should be fixed:

image

> ops seems like it's the same case as David mentioned

Indeed it is the same usecase.

**Review by datho7561 — APPROVED** [review]
Works very well. Thank you, Angelo!

**Comment by angelozerr** [comment]
Thanks so much @datho7561 @JessicaJHee  for your great review.

Now as we have proper range and we have support for multiple errors it would be very nice to provide code actions for each error code.

I think it will not an hatd task. 

If you have time and you are interested dont hesitate to create pas. Thanks!

**Pull request merged**
