### PR TITLE
Duplicate completion options in with deployment JAR

### LINKED ISSUE #137: Duplicate completion options in Gradle projects
There are duplicate completion items for  `quarkus.application.name` and `quarkus.application.version`.

The duplication items show up consistently.

image

To reproduce this bug:

* Clone https://github.com/xorye/sample-quarkus-gradle-project
* Install latest Quarkus Tools for VS Code: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus
* Open src/main/resources/application.properties
* Invoke completion (Ctrl + Space)

### PR DESCRIPTION
**Pull request by angelozerr**
Duplicate completion options in Gradle projects #137

Fixes #137

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
@xorye please test my PR and tell if it fixes your problem with duplicate Quarkus properties. I need to write test.

**Comment by angelozerr** [comment]
@jeffmaury I think you should do the same thing for IJ

**Comment by fbricon** [comment]
Can you add tests?

**Comment by xorye** [comment]
@angelozerr I am still getting the same behaviour described in https://github.com/redhat-developer/quarkus-ls/issues/137

**Comment by fbricon** [comment]
fix works for me

**Comment by angelozerr** [comment]
@xorye are you sure that you have build the JDT LS extension with `npm run build-ext` ?

**Comment by xorye** [comment]
@angelozerr oops, sorry. I didn't build the JDTLS extension.

Just tried it and I get no duplicates.

**Comment by xorye** [comment]
Since this is a draft PR, I'm not sure if this is expected but for a Gradle project with Quarkus version 0.28.1, I've noticed the `quarkus.application.name` and `quarkus.application.version` are now gone.

image

You can create a Gradle Quarkus project with version Quarkus 0.28.1 with:
```
mvn io.quarkus:quarkus-maven-plugin:0.28.1:create \
    -DprojectGroupId=my-groupId \
    -DprojectArtifactId=my-artifactId \
    -DprojectVersion=my-version \
    -DclassName="org.my.group.MyResource" \
    -Dextensions="resteasy-jsonb"
    -DbuildTool=gradle
```
The above command is from the Quarkus guide: https://quarkus.io/guides/gradle-tooling#project-creation

**Comment by angelozerr** [comment]
@fbricon test have been written. Tell me if you need some changes.

**Comment by xorye** [comment]
@angelozerr I've tried:
```

**Comment by xorye** [comment]
Oops, I'm sorry, I didnt mean to "Close and comment".

**Comment by angelozerr** [comment]
> again, and I don't get the problem I explained in my previous comment anymore

Thanks for the feedback. @fbricon can we merge this PR?

**Pull request merged**
