### PR TITLE
Remove unexpected nested-content parameter inserted in Quick Fix

### LINKED ISSUE #841: Quick fix to insert all missing attributes for user tag in Qute file adds a `nested-content` attribute
Let's say you have a user tag: (this is one from quarkus-renarde-todo)

`formElement.html`:
```qute-html
<label class="form-label" for="{name}">{label}</label>
<div class="mb-3 {class??}">
    {nested-content}
{#ifError name}
    <span class="invalid-feedback">​{#error name/}</span>​
{/ifError}
</div>
```

and you reference it from another Qute template like this:

```qute-html
{#formElement}
  <h3>Hello!</h3>
{/}
```

Then there is a quick fix that appears on `#formElement` to add all the missing attributes to the user tag. However, this quick fix adds an attribute called `nested-content`. However, `nested-content` [is a special key that gets replace with the content of the user tag](https://quarkus.io/guides/qute-reference#user_tags) (in this case `<h3>Hello!</h3>`). It doesn't makes sense to add it as an attribute with the quick fix.

### PR DESCRIPTION
**Pull request by JessicaJHee**
Fixes #841

### CODE REVIEW

**Comment by datho7561** [comment]
Looks pretty good, but there is a related corner case:

If you have a user tag `myTag.html`:

```
{it}
```

and you reference it:
```
{#myTag}
{/myTag}
```

- The old behaviour was to generate `{#myTag it="it"}`
- The new behaviour (with this PR) is that the code action does nothing and the warning doesn't go away when you apply the code action
- The correct behaviour is {#myTag ""}, since `it` refers to the first parameter without a name (see https://quarkus.io/guides/qute-reference#user_tags)

I'm wondering if you want to address this in this PR or should I file an issue so that someone will eventually get to it?

**Comment by JessicaJHee** [comment]
> * The correct behaviour is {#myTag ""}, since `it` refers to the first parameter without a name (see https://quarkus.io/guides/qute-reference#user_tags)

Thank you for pointing this case out! I've made some changes and added a test case, please let me know if I've understood the problem correctly.

**Comment by datho7561** [comment]
PR seems to be good, but there are test failures: it seems like adding a new user tag to one of the test projects affected a test that counts the number of completion items.

**Review by datho7561 — APPROVED** [review]
Looks good. Thanks, Jessica!

**Pull request merged**
