### PR TITLE
Definition for user tag parameter

### LINKED ISSUE #789: Definition for user tag parameter
Given this user tag `foo.html`

`{bar}`

It should be nice to go to the declaration from the template which declares the user tag:

`{#foo b|ar="" }`

The definition on bar should jump to the bar object part of foo.html.

Here a demo:

QuteUserTagDefinition

### PR DESCRIPTION
**Pull request by angelozerr**
Definition for user tag parameter

Fixes #789

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
Here a demo:

QuteUserTagDefinition

**Comment by datho7561** [comment]
What should happen if the user tag references the parameter many times?

**Comment by angelozerr** [comment]
> What should happen if the user tag references the parameter many times?

It go to the first definition.

**Comment by datho7561** [comment]
Hmm. I think it would be nice if we could show all the places it's used in the custom tag, but maybe that's more suited for "references".

Also, if you have a type declaration of the parameter at the top of the custom tag template, it would be nice if "go to definition" went to that.

**Comment by angelozerr** [comment]
> Hmm. I think it would be nice if we could show all the places it's used in the custom tag

Ok I close this PR, and I created a new one at https://github.com/redhat-developer/quarkus-ls/pull/792 but it is in draft because it is linked to https://github.com/redhat-developer/quarkus-ls/pull/791 (please review it before).

**Comment by angelozerr** [comment]
> Hmm. I think it would be nice if we could show all the places it's used in the custom tag, but maybe that's more suited for "references".

Please see the new PR https://github.com/redhat-developer/quarkus-ls/pull/794

**Pull request closed without merging**
