### PR TITLE
Add support for MicroProfile REST properties

### PR DESCRIPTION
**Pull request by angelozerr**
Add support for MicroProfile REST properties

See https://github.com/redhat-developer/vscode-quarkus/issues/104

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
To test this PR, I suggest you that you play with the project used for JDT test `com.redhat.microprofile.jdt.test/projects/maven/rest-client-quickstart` and try to open completion, hover validation in application.properties like the following demo:

MPRestDemo

**Comment by xorye** [comment]
@angelozerr this is working well for me, I'd say this can be merged.

**Comment by xorye** [comment]
One thing I found strange was the documentation for `mp-rest/scope`:
image

It says "as mentioned above" which doesn't make sense in this context.

But I'm afraid we can't do anything about this?

**Comment by angelozerr** [comment]
> But I'm afraid we can't do anything about this?

This description is hard coded in the JDT LS extension. I removed it.

**Comment by angelozerr** [comment]
Thanks @xorye for your review!

**Pull request merged**
