### PR TITLE
Upversion to 0.17.0

### PR DESCRIPTION
**Pull request by datho7561**
Signed-off-by: David Thompson <davthomp@redhat.com>

### CODE REVIEW

**Review by JessicaJHee — APPROVED** [review]
LGTM :+1:

**Comment by datho7561** [comment]
Good catch, I'll investigate. There should have been a lsp4mp snapshot build, but it looks like the build pipeline failed. I'll rerun it, then rerun this test suite.

**Comment by datho7561** [comment]
I've run it twice and the tests have failed both times. I'll investigate if I can reproduce the test failure.

**Comment by datho7561** [comment]
I can reproduce the test failure locally, but it only happens occasionally.

**Comment by datho7561** [comment]
I reran the lsp4mp snapshot build and skipped tests to ensure it released (I confirmed a while back that the tests for lsp4mp were passing locally). Hopefully the build works here.

**Pull request merged**
