### PR TITLE
Add rsync deployment to download.jboss.org

### LINKED ISSUE #124: Deploy quarkus.jdt update site to download.jboss.tools
Following #76 and #117 that allowed deploying quarkus-ls JARs to Nexus, it would be good to have quarkus-jdk update site deployed to download.jboss.org

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #124

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
@fbricon this will deploy to https://download.jboss.org/jbosstools/vscode/snapshots/quarkus-jdt/ not sure the vscode prefix is adequate but feel free to comment

**Comment by jeffmaury** [comment]
This is a WIP. It does not yet clean up old update sites so I need to understand how the cleanup stuff is done before merging

**Comment by angelozerr** [comment]
@jeffmaury you could mark your PR as Draft.

**Comment by jeffmaury** [comment]
This PR is now ready. The update site is now deployed under: download.jboss.org/tools/vscode/snapshots/builds/quarkus-jdt

**Pull request merged**
