### PR TITLE
Qute now support optional end tags for sections

### LINKED ISSUE #879: Qute now support optional end tags for sections
https://github.com/quarkusio/quarkus/pull/33296#event-9223149832

This is only for `let` and `include`

image

### PR DESCRIPTION
**Pull request by angelozerr**
Qute now support optional end tags for sections

Fixes #879

### CODE REVIEW

**Comment by angelozerr** [comment]
To try this PR, open https://github.com/ia3andy/quarkus-blast/blob/main/src/main/resources/templates/GameController/game.html

**Comment by datho7561** [comment]
If you make the following change to the file (use `{#let ...}` in an `{#if}` block) :

```
diff --git a/src/main/resources/templates/GameController/game.html b/src/main/resources/templates/GameController/game.html
index bff6b4e..721483c 100644
--- a/src/main/resources/templates/GameController/game.html
+++ b/src/main/resources/templates/GameController/game.html
@@ -3,6 +3,7 @@
   {#if game}
     <div class="text-center game-container d-flex flex-grow-1 flex-column">
       <div class="flex-grow-1 justify-content-center d-flex flex-column order-lg-1">
+        {#let sandwich='salami'}
         {#include GameController/partials/grid.html}{/include}
         {#include GameController/partials/score.html}{/include}
       </div>
```

Then I get the following diagnostic:

```
Parser error: unterminated section [else] detected
```

**Comment by angelozerr** [comment]
Good catch! Let me try fixing that.

**Comment by angelozerr** [comment]
@datho7561 please retry it

**Comment by JessicaJHee** [comment]
@angelozerr I noticed the same problem and can confirm now it is fixed!

**Comment by angelozerr** [comment]
> @angelozerr I noticed the same problem and can confirm now it is fixed!

Thanks for your feedback!

**Comment by angelozerr** [comment]
Ok CI build is working again.

**Review by datho7561 — APPROVED** [review]
Looks good! Thanks, Angelo!

**Comment by angelozerr** [comment]
Thanks @datho7561 @JessicaJHee  for your review!

**Pull request merged**
