### PR TITLE
Don't show data model completion inside end tag section

### LINKED ISSUE #446: Don't show data model completion inside tag section
```
{#with data}
{/}

```
proposes data when code completion after {

### PR DESCRIPTION
**Pull request by angelozerr**
Don't show data model completion inside end tag section

Fixes #446

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
Completion is fully broken for me ex {data. completion is proposing data after the dot. Seeing a lot of NPE in the LS

**Comment by angelozerr** [comment]
> Completion is fully broken for me ex {data. completion is proposing data after the dot.

Need to write more tests to fix your issue.

>  Seeing a lot of NPE in the LS

Which NPE? I noticed that we have NPE with outline (symbols) when expression is not closed. I need to fix it too. is it this NPE kind?

**Comment by angelozerr** [comment]
> Completion is fully broken for me ex {data. completion is proposing data after the dot. 

I think this issue exists in the master too. If you close the expression it should work. I'm fixing that in this PR.

**Comment by angelozerr** [comment]
@jeffmaury please retry. It should work better now and I have wriiten several test with completion with expression which is not closed. 

I started to write test for symbols (tests which failed with some NPE). Those tests should be improved in the future with another usecases.

**Comment by fbricon** [comment]
Doesn't seem to work. Either I don't get completion at all or the with'ed object is still proposed in completion
Screenshot 2021-11-26 at 11 31 55
Screenshot 2021-11-26 at 11 32 36

**Comment by fbricon** [comment]
My 2nd case is apparently invalid anyway (see #450}

**Comment by jeffmaury** [comment]
Seems to be an issue with stacking #416 

```
{@qute1.MyData data}
{data.available}
{#with data}
{#with stringCollection}
{}
</with>
{/with}
```

image

**Comment by angelozerr** [comment]
> Doesn't seem to work. Either I don't get completion at all 

I suppose you speak about snippets completion with each, for, etc. It's fixed and I wrote some tests.

> or the with'ed object is still proposed in completion

It's vscode completion which shows tokens, this completion doesn't comes from the Qute LS. You have the same problem with vscode-java:

image

**Comment by angelozerr** [comment]
@fbricon @jeffmaury do you think we could merge this PR? There is a problem with #with but it's an another issue.

**Comment by fbricon** [comment]
AFAICT, this PR doesn't fix the issue. item is still proposed inside the tag section
Screenshot 2021-11-29 at 13 28 16

**Comment by jeffmaury** [comment]
> AFAICT, this PR doesn't fix the issue. item is still proposed inside the tag section Screenshot 2021-11-29 at 13 28 16

Which sounds legit to me because it's part of the upper context, no ?

**Comment by angelozerr** [comment]
> Which sounds legit to me because it's part of the upper context, no ?

Exactly you can reusue inside #width the input data model. To avoid some confuse, you can use the data namespace (`data:item`). In other words you can write:

```
{@org.acme.Item item}
{#with item}
    {name}
    {item.name}
    {data:item.name}
{/}
```

**Comment by fbricon** [comment]
ok so what is this PR fixing then?

**Comment by angelozerr** [comment]
`|` is used whre completion is triggered:

 * Case 1:

```
{#with data}
{|/}
```

if you open completion inside `{/}` it should not provide data model.

 * Case 2:

 * `{|}` should show data model
 * `{{|}}` should NOT show data model
 * `{{{|}}}` should show data model

**Comment by angelozerr** [comment]
This PR doesn't show completion inside end tag section, in master it shows:

image

It fixes NPE with outline when your template contains not closed expression. For instance type just:

`{`

and in master you should see NPE:

```
Caused by: java.lang.NullPointerException: Property must not be null: range
	at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
	at org.eclipse.lsp4j.DocumentSymbol.<init>(DocumentSymbol.java:89)
	at org.eclipse.lsp4j.DocumentSymbol.<init>(DocumentSymbol.java:99)
	at com.redhat.qute.services.QuteSymbolsProvider.findDocumentSymbols(QuteSymbolsProvider.java:56)
	at com.redhat.qute.services.QuteSymbolsProvider.findDocumentSymbols(QuteSymbolsProvider.java:39)
	at com.redhat.qute.services.QuteLanguageService.findDocumentSymbols(QuteLanguageService.java:124)

```

It fixes too problem with property/method which is not displayed when expression is not closed (and you have none content after).

`{item.` should show method, but in master it shows again item:

image

**Comment by fbricon** [comment]
Thanks @angelozerr

**Pull request merged**
