### PR TITLE
fix: add languageId filter for options similar to microprofile

### PR DESCRIPTION
**Pull request by angelozerr**
fix: add languageId filter for options similar to microprofile

### CODE REVIEW

**Comment by datho7561** [comment]
I don't think that Qute files are working properly. I'll double check on my end though.

**Review by datho7561 — CHANGES_REQUESTED** [review]
Completion, validation, and go to definition aren't working in Qute files

**Comment by angelozerr** [comment]
Thanks for your feedback.

Let me investigate the problem.

**Comment by angelozerr** [comment]
> Completion, validation, and go to definition aren't working in Qute files

My bad, I forgot to push my work. Sorry to have loosed your time  -(

Please re-retry it.

**Comment by datho7561** [comment]
Most of the features are working now, but I still don't see validation.

**Comment by datho7561** [comment]
I'm getting `textDocument/publishDiagnostics` messages from the server, but they are all empty

**Review by datho7561 — APPROVED** [review]
Something is up with Qute validation in vsocde-quarkus (see #1000). The other features seem to be working and the code seems reasonable. If validation is working in intellij-quarkus, feel free to merge.

**Pull request merged**
