### PR TITLE
Update lsp4mp to 0.13.2

### PR DESCRIPTION
**Pull request by datho7561**
Also, bump to 4.35 i builds

### CODE REVIEW

**Review by rgrunber — APPROVED** [review]
LGTM.

**Review by rgrunber — APPROVED** [review]
Ah.. so there is a snapshot to Nexus reference. Hopefully we can just live with that for now.

**Comment by datho7561** [comment]
> Nexus reference

oh yeah oops. it should be good for the time being. just want to sure I can make the tests pass somewhere first

**Comment by datho7561** [comment]
Back to 0.13.2, the tests pass there. That would mean the bug is in lsp4mp.

**Pull request merged**
