### PR TITLE
Support {/} end tag section correctly

### LINKED ISSUE #460: Duplicate items when completing subclass of an object
I have Data extends Item. When completing on data, I can see duplicate methods:

Screenshot 2021-11-29 at 11 45 09

### LINKED ISSUE #464: Support {/} end tag section correctly
Support `{/}` end tag section correctly, in other words this short syntax should be supported to create a proper AST and consider the section is closed.

We can see the problem with highlight:

image

we should have:

image

By fixing this issue, I noticed that start/end tag offset are wrong and completion have not correct behaviour in some cases.

 * with #for section:

image

we should have this completion result:

image

### PR DESCRIPTION
**Pull request by angelozerr**
Support {/} end tag section correctly

Fixes #464

Signed-off-by: azerr <azerr@redhat.com>

### CODE REVIEW

**Comment by fbricon** [comment]
The change has nothing to do with the PR description/commit message

**Comment by angelozerr** [comment]
> The change has nothing to do with the PR description/commit message

Sorry I fixed it.

**Comment by angelozerr** [comment]
@fbricon the PR is ready to review it. See my comments at https://github.com/redhat-developer/quarkus-ls/issues/464#issue-1068154239

**Comment by fbricon** [comment]
Thanks @angelozerr!

**Pull request merged**
